def error_msg(exception):
    return {
        "error": str(exception)
    }